### ISSUE TITLE
Update Styles to Add Additional Functionality

### ISSUE THREAD

**Issue by christopherhein** [christopherhein/workshopper#3]
All styles that need to be modified should be added here.

```css
.literalblock.output pre {
  background-color: #232F3F;
  color: #fff
}

.subheader, #content #toctitle, .admonitionblock td.content > .title, .audioblock > .title, .exampleblock > .title, .imageblock > .title, .listingblock > .title, .literalblock > .title, .stemblock > .title, .openblock > .title, .paragraph > .title, .quoteblock > .title, table.tableblock > .title, .verseblock > .title, .videoblock > .title, .dlist > .title, .olist > .title, .ulist > .title, .qlist > .title, .hdlist > .title, .hljs-type, .hljs-string, .hljs-number, .hljs-selector-id, .hljs-selector-class, .hljs-quote, .hljs-template-tag, .hljs-deletion {
  color: #ec7211;
}

pre code {
  max-height: 400px;
  overflow: scroll;
}
```

- [ ] In `public/css/custom.css` remove line 39's padding
- [ ] In `public/css/custom.css` make line 162 - `.literalblock pre, .literalblock pre[class], .listingblock pre, .listingblock pre[class] { border: 0px; background-color: #F0F3F5; -webkit-border-radius: 5px; border-radius: 5px; padding: 0.4em 0.5em; word-wrap: break-word; }`

This pulled from - https://github.com/mandusm/workshopper/commit/258341e8a752619c9e7a303cec26cf3b84e61dbb

@mandusm do you see anything I missed here?
